### ISSUE TITLE
Basic Question 

### ISSUE THREAD

**Issue by peros550** [ageorgios/homebridge-sonoff-tasmota-http#10]
Hi Giorgo, 

If I use this plugin in homebridge, then I would not need to install a MQTT broker? So right now I have the following communication path 

Sonoff with Tasmota firm <--> MQTT broker <--> Homebridge

then it would be like this: 
Sonoff with Tasmota firm <-->  Homebridge

Eyxaristo polu,
Yiannis

**Comment by razer4908** [comment]
Correct, you dont need MQTT with this Plugin. Works like a charm :)
