### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by jakesza** [ageorgios/homebridge-sonoff-tasmota-http#13]
Hi, is there any way that you can add status update, so if you are using a Sonoff T1, and the switch is used to turn on something instead of http request, homekit still thinks the switch is off.

I do not want to use mqtt, http is far superior and simpler.

**Comment by ageorgios** [comment]
the status is checked every time the home app checks for status. If the event was driven from outside (like switching off a device from the device button) there is no way sonoff can send the event other than mqtt.
