### ISSUE TITLE
no device found

### ISSUE THREAD

**Issue by razvanu** [ageorgios/homebridge-sonoff-tasmota-http#15]
Hi, i'm using this version https://www.npmjs.com/package/homebridge-sonoff-th-tasmota-http but i can't see device in apple homebridge
can you help?

plugin is loaded just fine
```
[2019-3-2 17:20:57] ---
[2019-3-2 17:20:59] Loaded plugin: homebridge-sonoff-tasmota-http
[2019-3-2 17:20:59] Registering accessory 'homebridge-sonoff-tasmota-http.SonoffTasmotaHTTP'
[2019-3-2 17:20:59] ---

```

**Comment by i3laze** [comment]
Next thing is you should add your particular device into HomeBridge Config.
Like:
{
  "accessory": "SonoffTasmotaHTTP",
  "name": "Kitchen",
  "hostname": "192.168.1.5"
}

You’d better make DHCP Reservation for the device on your router, otherwise IP address will change eventually.

**Comment by razvanu** [comment]
ok, just added with ip, set the password too

`        {
        "accessory": "SonoffTasmotaHTTP",
        "name": "Sonoff",
        "password": "xxxxxxxxx",
        "hostname": "192.168.1.xyz"
        }
`
thanks, it's working now
