### ISSUE TITLE
Sonoff Status Commands Return as JSON

### ISSUE THREAD

**Issue by alexymik** [ageorgios/homebridge-sonoff-tasmota-http#2]
Sonoff-Tasmota firmware version 5.10.0b

I noticed that the replies from the Sonoff are in JSON format. 

Example:
```json
{"POWER":"ON"}
```

The code as-is now returns `undefined` for the accessory state which causes Homebridge to lock up in a strange state.

I rewrote the accessory functions to use `JSON.parse` successfully, will commit soon

**Comment by ageorgios** [comment]
I have noticed it too but found no time to fix it.
The pull request would be welcome.

**Comment by alexymik** [comment]
I sent the request -- however I have no idea if the older versions of the firmware work the way you have it in your original version. Not backwards compatible...
