### ISSUE TITLE
Unable to connect Homebridge

### ISSUE THREAD

**Issue by GinSoakedBoy** [ageorgios/homebridge-sonoff-tasmota-http#4]
I have been unable to get Homebridge to connect. Here is an excerpt from my. config.json:
{
  "accessory": "SonoffTasmotaHTTP",
  "name": "Bedside Lamp",
  "hostname": "sonoff-3993.local"
		}

Everything is working fine through the Tasmota web interface.

**Comment by ageorgios** [comment]
The Tasmota compatible version of the plugin is 5.10.0b and later

If you need compatibility with previous Tasmota versions, fork this commit: https://github.com/ageorgios/homebridge-sonoff-tasmota-http/tree/6f73a32fd8ae01f16813f8f0bd3844d3da469e4d

**Comment by GinSoakedBoy** [comment]
I only see version 5.10.0 on the Tasmota Github, where can I download 5.10.0b?

**Comment by ageorgios** [comment]
you compile it yourself or wait 1 week or so that the newest version is compiled and uploaded
