### ISSUE TITLE
Inform about state Lights after switch on wall physical button

### ISSUE THREAD

**Issue by erokoder** [ageorgios/homebridge-sonoff-tasmota-http#9]
Hello All,

I have this scheme wiring: http://prntscr.com/i0qrfb

I used homebridge plugin and iphone app HOME and I have problem about inform state.

Example:

State Lights on HOME app is OFF.
Turn on Lights with HOME app on R1 relay, snd Sonoff PRO switch reley and Lights is ON. On app HOME change state to ON.
When I pressing physical key "WALL SWITHC" Disconnect Electric Cricuit and turn off Light.
State continue ON on HomeAPP.
How to inform app that state is change? Can you help me this plugin?
Rade

**Comment by ageorgios** [comment]
It does not support live inform for changes from the physical button, although if you close and relaunch the home app again and it searches for status, the right status will be shown.

**Comment by erokoder** [comment]
There is a possibility to add this functionality in this plugin?

**Comment by ageorgios** [comment]
you have to use the mqtt plugin for this
